import { describe, expect, it } from 'vitest';
import { FakeDir } from '../fs/fakeFs';
import { archiveLoadOrder, archiveNamesFor } from './archives';
import { iniValue, isMo2Instance, loadMo2Instance, parseModlist, parsePluginList } from './mo2';
import { Overlay, mo2Layers } from './overlay';

const MODLIST = `# This file was automatically generated by Mod Organizer.
+My Dungeon
-Disabled Retexture
+Imperial Kit Fixes
-Tools_separator
+DLC Dragonborn
+DLC Dawnguard
*DLC: HearthFires
`;

const PLUGINS = `# This file was automatically generated by Mod Organizer.
*Skyrim.esm
*Update.esm
*Dawnguard.esm
Missing.esp
*Dragonborn.esm
*MyDungeon.esp
`;

function instance(): FakeDir {
  return new FakeDir('MO2', {
    'ModOrganizer.ini':
      '[General]\ngameName=Skyrim Special Edition\nselected_profile=@ByteArray(Default)\n\n[Settings]\nx=1\n',
    mods: new FakeDir('mods', {
      'My Dungeon': new FakeDir('My Dungeon', {
        'MyDungeon.esp': 'TES4-md',
        meshes: new FakeDir('meshes', { 'customimpfreewall01.nif': 'nif' }),
      }),
      'Imperial Kit Fixes': new FakeDir('Imperial Kit Fixes', {
        meshes: new FakeDir('meshes', {
          dungeons: new FakeDir('dungeons', {
            imperial: new FakeDir('imperial', {
              smallhall: new FakeDir('smallhall', { 'imphall1way01.nif': 'fixed' }),
            }),
          }),
        }),
      }),
      'DLC Dragonborn': new FakeDir('DLC Dragonborn', {
        'Dragonborn.esm': 'TES4-db',
        'Dragonborn.bsa': 'BSA',
      }),
      'DLC Dawnguard': new FakeDir('DLC Dawnguard', {
        'Dawnguard.esm': 'TES4-dg',
        'Dawnguard.bsa': 'BSA',
      }),
      'Disabled Retexture': new FakeDir('Disabled Retexture', {
        'Skyrim - Textures0.bsa': 'BSA-disabled',
      }),
    }),
    profiles: new FakeDir('profiles', {
      Default: new FakeDir('Default', { 'modlist.txt': MODLIST, 'plugins.txt': PLUGINS }),
      Testing: new FakeDir('Testing', {
        'modlist.txt': '+DLC Dawnguard\n',
        'plugins.txt': '*Skyrim.esm\n',
      }),
    }),
  });
}

function stockData(): FakeDir {
  return new FakeDir('Data', {
    'Skyrim.esm': 'TES4',
    'Update.esm': 'TES4',
    'Skyrim - Meshes0.bsa': 'BSA',
    'Skyrim - Textures0.bsa': 'BSA-stock',
    'HearthFires.esm': 'TES4',
    'HearthFires.bsa': 'BSA',
  });
}

describe('parsers', () => {
  it('reads modlist flags, separators and unmanaged entries', () => {
    const entries = parseModlist(MODLIST);
    expect(entries.map((e) => [e.name, e.enabled, e.managed, e.separator])).toEqual([
      ['My Dungeon', true, true, false],
      ['Disabled Retexture', false, true, false],
      ['Imperial Kit Fixes', true, true, false],
      ['Tools_separator', false, true, true],
      ['DLC Dragonborn', true, true, false],
      ['DLC Dawnguard', true, true, false],
      ['DLC: HearthFires', true, false, false],
    ]);
  });

  it('reads plugins.txt enabled flags and loadorder.txt', () => {
    expect(parsePluginList(PLUGINS).filter((p) => !p.enabled)).toEqual([
      { name: 'Missing.esp', enabled: false },
    ]);
    expect(parsePluginList('A.esp\nB.esp\n', true).map((p) => p.name)).toEqual(['A.esp', 'B.esp']);
  });

  it('reads INI values, unwrapping @ByteArray', () => {
    const ini =
      '[General]\nselected_profile=@ByteArray(My Profile)\n[Settings]\nselected_profile=other\n';
    expect(iniValue(ini, 'general', 'Selected_Profile')).toBe('My Profile');
    expect(iniValue(ini, 'Settings', 'selected_profile')).toBe('other');
    expect(iniValue(ini, 'Nope', 'x')).toBeUndefined();
  });

  it('derives archive names from a plugin name', () => {
    expect(archiveNamesFor('Dawnguard.esm')).toEqual(['Dawnguard.bsa', 'Dawnguard - Textures.bsa']);
  });
});

describe('loadMo2Instance', () => {
  it('detects an instance and picks the profile from the ini', async () => {
    const inst = instance();
    expect(await isMo2Instance(inst)).toBe(true);
    expect(await isMo2Instance(new FakeDir('x'))).toBe(false);
    const layout = await loadMo2Instance(inst);
    expect(layout.profile.name).toBe('Default');
    expect(layout.mods.map((m) => m.name)).toEqual([
      'My Dungeon',
      'Imperial Kit Fixes',
      'DLC Dragonborn',
      'DLC Dawnguard',
    ]);
    expect(layout.plugins).toEqual([
      'Skyrim.esm',
      'Update.esm',
      'Dawnguard.esm',
      'Dragonborn.esm',
      'MyDungeon.esp',
    ]);
    expect(layout.warnings).toEqual([]);
  });

  it('accepts an explicit profile and warns about missing folders', async () => {
    const inst = instance();
    (await inst.getDirectoryHandle('mods')).removeEntry?.('DLC Dawnguard');
    const layout = await loadMo2Instance(inst, 'Testing');
    expect(layout.profile.name).toBe('Testing');
    expect(layout.mods).toEqual([{ name: 'DLC Dawnguard' }]);
    expect(layout.warnings).toEqual(['mod folder missing: mods/DLC Dawnguard']);
  });
});

describe('Overlay', () => {
  it('lets the highest-priority mod win, then the game Data folder', async () => {
    const layout = await loadMo2Instance(instance());
    const overlay = new Overlay(mo2Layers(layout, stockData()));
    expect(overlay.layers.map((l) => l.name)).toEqual([
      'My Dungeon',
      'Imperial Kit Fixes',
      'DLC Dragonborn',
      'DLC Dawnguard',
      'Data (game)',
    ]);

    expect((await overlay.resolveFile('Dawnguard.esm'))?.layer.name).toBe('DLC Dawnguard');
    expect((await overlay.resolveFile('skyrim.esm'))?.layer.name).toBe('Data (game)');
    expect(
      (await overlay.resolveFile('meshes/dungeons/imperial/smallhall/imphall1way01.nif'))?.layer
        .name,
    ).toBe('Imperial Kit Fixes');
    expect(await overlay.resolveFile('meshes/nothing.nif')).toBeUndefined();
    // a disabled mod never contributes
    expect((await overlay.resolveFile('Skyrim - Textures0.bsa'))?.layer.name).toBe('Data (game)');
  });

  it('merges directory listings across layers', async () => {
    const layout = await loadMo2Instance(instance());
    const overlay = new Overlay(mo2Layers(layout, stockData()));
    const plugins = await overlay.listFiles('', { suffix: '.esm' });
    expect(plugins.map((p) => `${p.name}@${p.layer.name}`)).toEqual([
      'Dawnguard.esm@DLC Dawnguard',
      'Dragonborn.esm@DLC Dragonborn',
      'HearthFires.esm@Data (game)',
      'Skyrim.esm@Data (game)',
      'Update.esm@Data (game)',
    ]);
    expect((await overlay.listFiles('meshes', { suffix: '.nif' })).map((f) => f.name)).toEqual([
      'customimpfreewall01.nif',
    ]);
  });
});

describe('archiveLoadOrder', () => {
  it('lists base archives then plugin archives in load order, from their winning layer', async () => {
    const layout = await loadMo2Instance(instance());
    const overlay = new Overlay(mo2Layers(layout, stockData()));
    const order = await archiveLoadOrder(overlay, [...layout.plugins, 'HearthFires.esm']);
    expect(order.map((a) => `${a.name}<${a.layer.name}>${a.source}`)).toEqual([
      'Skyrim - Meshes0.bsa<Data (game)>base',
      'Skyrim - Textures0.bsa<Data (game)>base',
      'Dawnguard.bsa<DLC Dawnguard>plugin',
      'Dragonborn.bsa<DLC Dragonborn>plugin',
      'HearthFires.bsa<Data (game)>plugin',
    ]);
  });
});

describe('Overlay listing cache', () => {
  it('lists each directory once across many lookups, and forgets on invalidate', async () => {
    const layout = await loadMo2Instance(instance());
    const data = stockData();
    const overlay = new Overlay(mo2Layers(layout, data));
    let calls = 0;
    const original = data.values.bind(data);
    data.values = () => {
      calls++;
      return original();
    };
    for (let i = 0; i < 10; i++) {
      expect((await overlay.resolveFile('Skyrim.esm'))?.layer.name).toBe('Data (game)');
      expect(await overlay.resolveFile('meshes/missing.nif')).toBeUndefined();
    }
    expect(calls).toBe(1);
    overlay.invalidate();
    await overlay.resolveFile('Skyrim.esm');
    expect(calls).toBe(2);
  });
});
