/**
 * V2 step 3 (R1): write a NavMesh generated by code into a copy of a plugin, then compare it
 * with what the Creation Kit made of it once finalized and saved.
 *
 * The NavMesh covers the grid cells of one placed tile or of every tile of the cell, at the floor of their grid level: the
 * tile is found with the catalogue the app analysed (cached in IndexedDB) and the grid derived
 * from the cell, so nothing is placed by hand. The real walkable shape comes at step 4.
 */
import { kvGet, readAll, writeFileAtomic } from '$lib/fs';
import {
  Plugin,
  decodeNvnm,
  findSubrecord,
  formIdHex,
  formIdIndex,
  recordSubrecords,
  toFormKey,
  type CellEntry,
  type NavMeshData,
} from '$lib/format/esp';
import type { Catalogue, Vec3 } from '$lib/catalogue/types';
import { deriveGrid, type DeriveResult } from '$lib/grid/derive';
import type { TilePlacement } from '$lib/grid/types';
import { piecesByFormKey } from '$lib/level/loadCell';
import { buildNavMesh, type TriangleIndices } from '$lib/navmesh/build';
import type { OverlayFileInfo } from '$lib/vfs';
import { bindProfileSelect, describeView, openDataView, type DataView } from './shared/dataView';

const $ = <T extends HTMLElement>(id: string) => document.getElementById(id) as T;
const logEl = $<HTMLPreElement>('log');
const log = (m: string, cls = '') => {
  const line = document.createElement('div');
  line.textContent = `${new Date().toLocaleTimeString()}  ${m}`;
  if (cls) line.className = cls;
  logEl.prepend(line);
};
const escape = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;');

const WRITTEN_KEY = 'poc.navmTile.written';

let view: DataView | null = null;
let catalogue: Catalogue | null = null;
let plugins: OverlayFileInfo[] = [];
let current: { info: OverlayFileInfo; bytes: Uint8Array; cells: CellEntry[] } | null = null;
let grid: DeriveResult | null = null;

function copyName(name: string): string {
  return name.replace(/\.esp$/i, '') + '.navtest.esp';
}

async function useView(next: DataView): Promise<void> {
  view = next;
  catalogue = (await kvGet<Catalogue>('catalogue:Imperial')) ?? null;
  plugins = (await next.overlay.listFiles('', { suffix: '.esp' })).filter(
    (p) => !p.name.toLowerCase().endsWith('.navtest.esp'),
  );
  $<HTMLSelectElement>('plugin').innerHTML = plugins
    .map((p, i) => `<option value="${i}">${escape(p.name)}  [${escape(p.layer.name)}]</option>`)
    .join('');
  $('status').textContent =
    `${describeView(next)} ${plugins.length} plugins visible. ` +
    (catalogue
      ? `Catalogue: ${catalogue.pieces.length} pieces.`
      : "No analysed catalogue: open the app's Catalogue page once, then reload.");
  $('status').className = catalogue ? 'ok' : 'err';
  $<HTMLButtonElement>('parse').disabled = plugins.length === 0 || !catalogue;
  bindProfileSelect($<HTMLSelectElement>('profile'), next, (v) => void useView(v));
}

$('parse').addEventListener('click', async () => {
  const info = plugins[Number($<HTMLSelectElement>('plugin').value)];
  if (!info) return;
  try {
    const bytes = await readAll(info.handle);
    const cells = await Plugin.parse(bytes, info.name).interiorCells();
    current = { info, bytes, cells };
    $<HTMLSelectElement>('cell').innerHTML = cells
      .map(
        (c, i) =>
          `<option value="${i}">${escape(c.info.editorId)} ${formIdHex(c.record.formId)}</option>`,
      )
      .join('');
    await loadTiles();
    log(`parsed ${info.name}: ${cells.length} interior cells`, 'ok');
  } catch (error) {
    log(`parse failed: ${(error as Error).message}`, 'err');
  }
});

async function loadTiles(): Promise<void> {
  if (!current || !catalogue) return;
  const kit = catalogue.kits[0];
  if (!kit?.module.xy || !kit.module.z) throw new Error('catalogue has no measured kit module');
  const plugin = Plugin.parse(current.bytes, current.info.name);
  const cell = (await plugin.interiorCells())[Number($<HTMLSelectElement>('cell').value)];
  const refs = cell ? await plugin.cellRefs(cell) : [];
  grid = deriveGrid(
    refs.map((r) => ({
      refFormKey: toFormKey(r.record.formId, plugin.masters, plugin.name),
      base: toFormKey(r.info.base, plugin.masters, plugin.name),
      pos: r.info.pos,
      rot: r.info.rot,
      scale: r.info.scale,
    })),
    piecesByFormKey(catalogue),
    { module: kit.module.xy, zModule: kit.module.z },
  );
  $<HTMLSelectElement>('tile').innerHTML =
    `<option value="-1">All ${grid.tiles.length} tiles</option>` +
    grid.tiles
      .map(
        (t, i) =>
          `<option value="${i}">${escape(t.pieceEditorId)} at [${t.cell.join(', ')}], ${t.occupied.length} cells</option>`,
      )
      .join('');
  $<HTMLButtonElement>('write').disabled = grid.tiles.length === 0;
  $('tiles-note').textContent =
    `${grid.tiles.length} tiles on the grid, ${grid.opaque.length} other references.`;
}
$('cell').addEventListener('change', () => void loadTiles());

/**
 * Two CCW triangles per grid cell the tiles occupy on their lowest level, at that level's floor
 * raised by `dz`; cells shared by several tiles are counted once and vertices are shared between
 * neighbouring cells of the same level.
 */
function tileCells(
  tiles: readonly TilePlacement[],
  g: DeriveResult,
  dz: number,
): { vertices: Vec3[]; triangles: TriangleIndices[] } {
  const { origin, module } = g.anchor;
  const vertices: Vec3[] = [];
  const index = new Map<string, number>();
  const vertex = (i: number, j: number, k: number) => {
    const key = `${i},${j},${k}`;
    let v = index.get(key);
    if (v === undefined) {
      v = vertices.length;
      vertices.push([
        origin[0] + i * module.xy,
        origin[1] + j * module.xy,
        origin[2] + k * module.z + dz,
      ]);
      index.set(key, v);
    }
    return v;
  };
  const floors = new Map<string, [number, number, number]>();
  for (const tile of tiles) {
    const level = Math.min(...tile.occupied.map((c) => c[2]));
    for (const [i, j, k] of tile.occupied) if (k === level) floors.set(`${i},${j},${k}`, [i, j, k]);
  }
  const triangles: TriangleIndices[] = [];
  for (const [i, j, k] of floors.values()) {
    triangles.push([vertex(i, j, k), vertex(i + 1, j, k), vertex(i + 1, j + 1, k)]);
    triangles.push([vertex(i, j, k), vertex(i + 1, j + 1, k), vertex(i, j + 1, k)]);
  }
  return { vertices, triangles };
}

$('write').addEventListener('click', async () => {
  if (!current || !grid) return;
  try {
    const choice = Number($<HTMLSelectElement>('tile').value);
    const tiles = choice === -1 ? grid.tiles : grid.tiles.slice(choice, choice + 1);
    if (tiles.length === 0) return;
    const dz = Number($<HTMLInputElement>('dz').value) || 0;
    const plugin = Plugin.parse(current.bytes, current.info.name);
    const cell = (await plugin.interiorCells())[Number($<HTMLSelectElement>('cell').value)];
    if (!cell) return;
    const { vertices, triangles } = tileCells(tiles, grid, dz);
    const nav = buildNavMesh(cell.record.formId, vertices, triangles);
    const record = plugin.addNavm(cell, nav);
    const name = copyName(current.info.name);
    await writeFileAtomic(current.info.layer.dir, name, plugin.write());
    localStorage.setItem(WRITTEN_KEY, JSON.stringify({ name, formId: record.formId, nav }));
    $('write-result').innerHTML =
      `Wrote <code>${escape(name)}</code>: NAVM ${formIdHex(record.formId)} over ${tiles.length === 1 ? escape(tiles[0]!.pieceEditorId) : `${tiles.length} tiles`} ` +
      `in ${escape(cell.info.editorId)}, ${vertices.length} vertices, ${triangles.length} triangles, ` +
      `floor raised by ${dz}. Load it alone in the CK (disable the original), ` +
      `Finalize, save, then compare below.`;
    $('write-result').className = 'ok';
    log(`copy written: ${name}, NAVM ${formIdHex(record.formId)}`, 'ok');
  } catch (error) {
    log(`write failed: ${(error as Error).message}`, 'err');
  }
});

function diffNav(before: NavMeshData, after: NavMeshData): string[] {
  const out: string[] = [];
  const count = (what: string, x: number, y: number) =>
    out.push(`${what}: ${x} -> ${y}${x === y ? '' : '  CHANGED'}`);
  count('vertices', before.vertices.length, after.vertices.length);
  count('triangles', before.triangles.length, after.triangles.length);
  count('edge links', before.edgeLinks.length, after.edgeLinks.length);
  count('door links', before.doorLinks.length, after.doorLinks.length);
  count('cover triangles', before.cover.length, after.cover.length);
  count('grid divisor', before.grid.divisor, after.grid.divisor);
  const moved = before.vertices.filter((v, i) => {
    const w = after.vertices[i];
    return !w || v.some((c, k) => Math.abs(c - w[k]!) > 0.01);
  }).length;
  out.push(`vertices moved or reordered: ${moved}`);
  let reordered = 0;
  let edges = 0;
  let flags = 0;
  before.triangles.forEach((t, i) => {
    const u = after.triangles[i];
    if (!u || t.vertices.some((v, k) => v !== u.vertices[k])) reordered++;
    else {
      if (t.edges.some((e, k) => e !== u.edges[k])) edges++;
      if (t.flags !== u.flags || t.coverFlags !== u.coverFlags) flags++;
    }
  });
  out.push(`triangles reordered: ${reordered}, edges changed: ${edges}, flags changed: ${flags}`);
  const afterFlags = [...new Set(after.triangles.map((t) => t.flags.toString(16)))].join(' ');
  out.push(`triangle flags after: ${afterFlags}`);
  const sameGrid = JSON.stringify(before.grid) === JSON.stringify(after.grid);
  out.push(`search grid identical: ${sameGrid}`);
  return out;
}

$('compare').addEventListener('click', async () => {
  try {
    const saved = localStorage.getItem(WRITTEN_KEY);
    if (!saved || !view) throw new Error('write a copy first');
    const { name, formId, nav } = JSON.parse(saved) as {
      name: string;
      formId: number;
      nav: NavMeshData;
    };
    const info = (await view.overlay.listFiles('', { suffix: '.esp' })).find(
      (p) => p.name === name,
    );
    if (!info) throw new Error(`${name} not found`);
    const plugin = Plugin.parse(await readAll(info.handle), info.name);
    const navms = plugin.recordsOfType('NAVM');
    const record =
      navms.find((r) => r.formId === formId) ??
      navms.find((r) => formIdIndex(r.formId) === plugin.ownIndex);
    if (!record) throw new Error(`no NAVM of the plugin itself in ${name}`);
    const subs = await recordSubrecords(record);
    const nvnm = findSubrecord(subs, 'NVNM');
    if (!nvnm) throw new Error('the NAVM has no NVNM');
    const after = decodeNvnm(nvnm.data);
    const lines = [
      `NAVM ${formIdHex(record.formId)}${record.formId === formId ? ' (same FormID)' : ' (FormID CHANGED)'}, ` +
        `fields ${subs.map((s) => s.type).join(', ')}, ${navms.length} NAVM in the file`,
      ...diffNav({ ...nav, grid: { ...nav.grid } }, after),
    ];
    $('compare-result').textContent = lines.join('\n');
    log(`compared ${name}`, 'ok');
  } catch (error) {
    log(`compare failed: ${(error as Error).message}`, 'err');
  }
});

openDataView()
  .then(useView)
  .catch((error: Error) => {
    $('status').textContent = error.message;
    $('status').className = 'err';
  });
